version: '3.7'
services:
  #Laravel App
  app:
    build:
      args:
        user: ubuntu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
      - ./src/composer.json:/var/www/composer.json:ro
      - ./src/composer.lock:/var/www/composer.lock
    networks:
      - mynetwork

  #Nginx Service
  nginx:
    container_name: appBackend
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 5310:80
    volumes:
      - ./src:/var/www
      - ./infra/docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - mynetwork
      - app_backend
  #Mysl Service
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ADMadm1234
      MYSQL_PASSWORD: ADMadm1234
      MYSQL_USER: admin
    volumes:
      - bundle_cache:/var/run/mysqld
    networks:
      - dbmysql
      - mynetwork
networks:
  mynetwork:
    driver: bridge
  dbmysql:
    name: dbmysql
  app_backend:
    name: app_backend
volumes:
  bundle_cache:
